# Generated by Django 4.1.5 on 2023-02-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='marca del auto', max_length=30)),
                ('modelo', models.CharField(help_text='modelo del auto', max_length=30)),
                ('precio', models.IntegerField(default=1, help_text='precio de reparacion o presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre del mecanico', max_length=30)),
                ('apellido', models.CharField(help_text='apellido del mecanico', max_length=30)),
                ('especializacion', models.CharField(help_text='especializacion del mecanico', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre de la pieza', max_length=30)),
                ('precio', models.IntegerField(default=1, help_text='precio de la pieza')),
                ('cantidad', models.IntegerField(default=1, help_text='cantidad de piezas')),
                ('caracteristicas', models.CharField(default='DEFAULT VALUE', help_text='caracteristicas de la pieza', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre de la pieza', max_length=30)),
                ('precio', models.IntegerField(default=1, help_text='precio de la pieza')),
                ('cantidad', models.IntegerField(default=1, help_text='cantidad de piezas')),
                ('caracteristicas', models.CharField(default='DEFAULT VALUE', help_text='caracteristicas de la pieza', max_length=150)),
            ],
        ),
    ]
