# Generated by Django 4.1.5 on 2023-02-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_autos_rep_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezas',
            name='caracteristicas',
        ),
    ]
