# Generated by Django 4.1.5 on 2023-02-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_autos_rep_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autos',
            name='rep_mod',
        ),
        migrations.AddField(
            model_name='autos',
            name='reparacion',
            field=models.CharField(default='', help_text='reparacion', max_length=600),
        ),
    ]
